### ISSUE TITLE
easy test feedback 

### ISSUE THREAD

**Issue by tdhock** [busttech/test-solutions-of-animint#1]
hi @busttech 
The easy test solution is ok.
It is good that you got the animint2pages function working.
But on https://busttech.github.io/deploy/ the colors you chose are potentially confusing.
Upper middle should be between lower middle and high, but it is below not classified.
You can change that by 
- set factor levels of income to the desired order
- or use limits argument of scale_color_manual

Also you should try to pick colors which are more different. For example I don't see any difference in color between the first three legend entries on my screen.
![image](https://github.com/user-attachments/assets/35fb24ba-8440-46c4-ab15-e91f79fed82f)

**Comment by busttech** [comment]
Thanks you sir for feedback,
I had made all changes you asked for,
 and now you can see changes in our web server  https://busttech.github.io/deploy/.
